name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC (5:30 AM IST)
  workflow_dispatch: # Allows manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Satvik-Roy
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*
          git commit -m "Update contribution snake" || exit 0
          git push
